"""Scheduled auto-generation of purchase orders from replenishment suggestions.

Runs on an interval (REPLENISHMENT_AUTO_PO_ENABLED). For every product past
its reorder point, picks the supplier most recently used for that product
(from purchase orders/invoices), skips products already covered by a pending
PO, and creates one draft purchase order per supplier. The PO is attributed
to the first active superuser (same pattern as the reservation sweep).
"""

from collections import defaultdict

from sqlalchemy.orm import Session

from app.core.replenishment import build_replenishment_suggestions
from app.models.product import Product
from app.models.purchase import Supplier
from app.models.user import User
from app.schemas.replenishment import PurchaseOrderFromSuggestionsCreate
from app.services.purchasing import (
    _products_already_in_pending_po,
    _supplier_for_products,
    create_purchase_order_from_replenishment,
)


def auto_generate_purchase_orders(
    db: Session,
    lookback_days: int = 30,
    tenant_id: int | None = None,
    min_stock_trigger: int = 0,
    actor: User | None = None,
) -> dict:
    """Create draft POs for products past reorder point. Idempotent per run.

    When ``tenant_id`` is given, only that tenant's products/suppliers are
    considered and ``actor`` should be a user of the same tenant. The
    effective reorder line is ``max(reorder_point, min_stock_trigger)``.
    """
    pending_products = _products_already_in_pending_po(db, tenant_id=tenant_id)
    query = db.query(Product)
    if tenant_id is not None:
        query = query.filter(Product.tenant_id == tenant_id)
    if min_stock_trigger > 0:
        from sqlalchemy import or_

        query = query.filter(
            or_(
                Product.stock_quantity <= Product.reorder_point,
                Product.stock_quantity <= min_stock_trigger,
            )
        )
    else:
        query = query.filter(Product.stock_quantity <= Product.reorder_point)
    candidates = [
        p
        for p in query.order_by(Product.id.asc()).all()
        if p.stock_quantity <= max(p.reorder_point, min_stock_trigger)
    ]
    candidates = [p for p in candidates if p.id not in pending_products]
    if not candidates:
        return {"generated": 0, "skipped_products": [], "po_ids": [], "suppliers": []}

    if actor is None:
        actor_query = db.query(User).filter(
            User.is_superuser.is_(True), User.is_active.is_(True)
        )
        if tenant_id is not None:
            actor_query = actor_query.filter(User.tenant_id == tenant_id)
        actor = actor_query.order_by(User.id.asc()).first()
    if not actor:
        return {
            "generated": 0,
            "skipped_products": [
                {"product_id": p.id, "reason": "no active superuser to own the PO"}
                for p in candidates
            ],
            "po_ids": [],
            "suppliers": [],
        }

    suggestions = build_replenishment_suggestions(
        db=db,
        products=candidates,
        lookback_days=lookback_days,
        min_stock_trigger=min_stock_trigger,
    )
    reorder_items = [
        item
        for item in suggestions
        if item.should_reorder and item.recommended_order_quantity > 0
    ]
    if not reorder_items:
        return {"generated": 0, "skipped_products": [], "po_ids": [], "suppliers": []}

    product_ids = [item.product_id for item in reorder_items]
    supplier_map = _supplier_for_products(db, product_ids, tenant_id=tenant_id)

    by_supplier: dict[int, list[int]] = defaultdict(list)
    skipped: list[dict] = []
    for item in reorder_items:
        supplier_id = supplier_map.get(item.product_id)
        if supplier_id is None:
            skipped.append(
                {"product_id": item.product_id, "reason": "no supplier history"}
            )
            continue
        by_supplier[supplier_id].append(item.product_id)

    po_ids: list[int] = []
    generated_suppliers: list[str] = []
    for supplier_id, supplier_product_ids in by_supplier.items():
        supplier = db.query(Supplier).filter(Supplier.id == supplier_id).first()
        if not supplier or not supplier.is_active:
            for product_id in supplier_product_ids:
                skipped.append(
                    {"product_id": product_id, "reason": "supplier inactive"}
                )
            continue
        purchase_order = create_purchase_order_from_replenishment(
            db=db,
            current_user=actor,
            tenant_id=supplier.tenant_id,
            payload=PurchaseOrderFromSuggestionsCreate(
                supplier_id=supplier_id,
                lookback_days=lookback_days,
                product_ids=supplier_product_ids,
                include_only_reorder=True,
                notes=(
                    f"Auto-generated by scheduled replenishment "
                    f"(lookback_days={lookback_days})"
                ),
            ),
            min_stock_trigger=min_stock_trigger,
        )
        po_ids.append(purchase_order.id)
        generated_suppliers.append(supplier.name)

    return {
        "generated": len(po_ids),
        "skipped_products": skipped,
        "po_ids": po_ids,
        "suppliers": generated_suppliers,
    }
