"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-08-12 00:07:44.252678

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _seed_rbac_defaults() -> None:
    """Seed the default RBAC permissions, roles, and role->permission grants."""
    permission_codes: dict[str, str] = {
        "products:manage": "Manage products and categories",
        "customers:manage": "Manage customers",
        "promotions:manage": "Manage promotions and discounts",
        "orders:manage": "Create and manage orders",
        "payments:manage": "Add order payments",
        "refunds:view": "View refunds",
        "refunds:create": "Create refunds",
        "inventory:view": "View inventory movements and suggestions",
        "purchasing:manage": "Manage suppliers, purchase orders, and invoices",
        "purchasing:approve": "Approve or reject purchase invoices",
        "reports:view": "View analytics and summary reports",
        "taxes:read": "View tax rules",
        "taxes:manage": "Manage tax rules",
        "settings:manage": "Manage system settings and localization",
        "users:manage_roles": "Assign roles and manage RBAC",
        "orders:release_reservations": "Release expired reservations",
    }
    permissions_table = sa.table(
        "permissions",
        sa.column("code", sa.String),
        sa.column("description", sa.String),
    )
    op.bulk_insert(
        permissions_table,
        [
            {"code": code, "description": desc}
            for code, desc in permission_codes.items()
        ],
    )

    role_definitions: dict[str, list[str]] = {
        "cashier": [
            "orders:manage",
            "payments:manage",
            "refunds:view",
            "refunds:create",
            "inventory:view",
            "taxes:read",
        ],
        "manager": [
            "products:manage",
            "customers:manage",
            "promotions:manage",
            "orders:manage",
            "payments:manage",
            "refunds:view",
            "refunds:create",
            "inventory:view",
            "purchasing:manage",
            "purchasing:approve",
            "reports:view",
            "taxes:read",
            "taxes:manage",
            "settings:manage",
            "orders:release_reservations",
        ],
        "admin": list(permission_codes.keys()),
    }
    roles_table = sa.table(
        "roles",
        sa.column("name", sa.String),
        sa.column("description", sa.String),
        sa.column("is_system", sa.Boolean),
    )
    op.bulk_insert(
        roles_table,
        [
            {"name": name, "description": f"Default {name} role", "is_system": True}
            for name in role_definitions
        ],
    )

    for role_name, codes in role_definitions.items():
        placeholders = ", ".join(f"'{c}'" for c in codes)
        op.execute(
            f"INSERT INTO role_permissions (role_id, permission_id) "
            f"SELECT r.id, p.id FROM roles r, permissions p "
            f"WHERE r.name = '{role_name}' AND p.code IN ({placeholders})"
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_categories_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_categories_name"), ["name"], unique=False)

    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("points_balance", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_customers_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_customers_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_customers_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_customers_phone"), ["phone"], unique=False)

    op.create_table(
        "localization_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("date_format", sa.String(), nullable=False),
        sa.Column("number_format", sa.String(), nullable=False),
        sa.Column("country_code", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("localization_settings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_localization_settings_id"), ["id"], unique=False
        )

    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_permissions_code"), ["code"], unique=True)
        batch_op.create_index(batch_op.f("ix_permissions_id"), ["id"], unique=False)

    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_roles_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_roles_name"), ["name"], unique=True)

    op.create_table(
        "suppliers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("contact_email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_suppliers_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_suppliers_name"), ["name"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)

    op.create_table(
        "drawer_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "opened_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("starting_cash", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("ending_cash", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("expected_cash", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("drawer_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_drawer_sessions_id"), ["id"], unique=False)

    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), nullable=True),
        sa.Column("min_stock", sa.Integer(), nullable=False),
        sa.Column("max_stock", sa.Integer(), nullable=True),
        sa.Column("reorder_point", sa.Integer(), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_products_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_sku"), ["sku"], unique=True)

    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "total_estimated_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("ordered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchase_orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_purchase_orders_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_purchase_orders_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_orders_supplier_id"), ["supplier_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_orders_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_refresh_tokens_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_token"), ["token"], unique=True
        )

    op.create_table(
        "role_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "role_id", "permission_id", name="uq_role_permissions_role_id_permission_id"
        ),
    )
    with op.batch_alter_table("role_permissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_role_permissions_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_role_permissions_permission_id"),
            ["permission_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_role_permissions_role_id"), ["role_id"], unique=False
        )

    op.create_table(
        "sync_event_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("client_event_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=True),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "client_event_id", "event_type", name="uq_sync_event_log_unique"
        ),
    )
    with op.batch_alter_table("sync_event_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sync_event_logs_client_event_id"),
            ["client_event_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sync_event_logs_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sync_event_logs_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sync_event_logs_idempotency_key"),
            ["idempotency_key"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sync_event_logs_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sync_event_logs_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_roles_user_id_role_id"),
    )
    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_roles_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_user_roles_role_id"), ["role_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_roles_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "promotions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("discount_type", sa.String(), nullable=False),
        sa.Column("discount_value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "min_order_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "max_discount_amount", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("applies_to", sa.String(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("promotions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_promotions_code"), ["code"], unique=True)
        batch_op.create_index(batch_op.f("ix_promotions_id"), ["id"], unique=False)

    op.create_table(
        "purchase_invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("purchase_order_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("invoice_number", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("invoice_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subtotal_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("variance_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("has_quantity_variance", sa.Boolean(), nullable=False),
        sa.Column("has_price_variance", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchase_invoices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_purchase_invoices_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_invoices_invoice_number"),
            ["invoice_number"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_invoices_purchase_order_id"),
            ["purchase_order_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_invoices_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_invoices_supplier_id"),
            ["supplier_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_invoices_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "purchase_order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity_ordered", sa.Integer(), nullable=False),
        sa.Column("quantity_received", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchase_order_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_purchase_order_items_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_order_items_product_id"),
            ["product_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_order_items_purchase_order_id"),
            ["purchase_order_id"],
            unique=False,
        )

    op.create_table(
        "shift_reconciliations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("drawer_session_id", sa.Integer(), nullable=False),
        sa.Column("closed_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "cash_sales_total", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "non_cash_sales_total", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("refunds_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("expected_cash", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("counted_cash", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cash_variance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "expected_non_cash", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "counted_non_cash", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "non_cash_variance", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("completed_order_count", sa.Integer(), nullable=False),
        sa.Column(
            "gross_sales_total", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("net_sales_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["drawer_session_id"],
            ["drawer_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shift_reconciliations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shift_reconciliations_closed_by_user_id"),
            ["closed_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_shift_reconciliations_drawer_session_id"),
            ["drawer_session_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_shift_reconciliations_id"), ["id"], unique=False
        )

    op.create_table(
        "tax_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tax_scope", sa.String(), nullable=False),
        sa.Column("tax_mode", sa.String(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tax_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tax_rules_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tax_rules_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tax_rules_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tax_rules_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tax_rules_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tax_rules_tax_mode"), ["tax_mode"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tax_rules_tax_scope"), ["tax_scope"], unique=False
        )

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("promotion_id", sa.Integer(), nullable=True),
        sa.Column("drawer_session_id", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("subtotal_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("discount_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "taxable_base_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "tax_total_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "grand_total_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paid_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("change_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "remaining_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("redeemed_points", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("reservation_status", sa.String(), nullable=False),
        sa.Column("reservation_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["drawer_session_id"],
            ["drawer_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["promotion_id"],
            ["promotions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_orders_user_idempotency"
        ),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_orders_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_orders_idempotency_key"), ["idempotency_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_orders_reservation_expires_at"),
            ["reservation_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_orders_reservation_status"),
            ["reservation_status"],
            unique=False,
        )

    op.create_table(
        "purchase_invoice_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("purchase_order_item_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("billed_quantity", sa.Integer(), nullable=False),
        sa.Column(
            "billed_unit_cost", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("expected_quantity", sa.Integer(), nullable=False),
        sa.Column(
            "expected_unit_cost", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("quantity_variance", sa.Integer(), nullable=False),
        sa.Column("price_variance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["purchase_invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_item_id"],
            ["purchase_order_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchase_invoice_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_purchase_invoice_items_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_invoice_items_invoice_id"),
            ["invoice_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_invoice_items_product_id"),
            ["product_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_invoice_items_purchase_order_item_id"),
            ["purchase_order_item_id"],
            unique=False,
        )

    op.create_table(
        "loyalty_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("transaction_type", sa.String(), nullable=False),
        sa.Column("points_delta", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("loyalty_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_loyalty_transactions_customer_id"),
            ["customer_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_loyalty_transactions_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_loyalty_transactions_order_id"), ["order_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_loyalty_transactions_transaction_type"),
            ["transaction_type"],
            unique=False,
        )

    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_order_items_id"), ["id"], unique=False)

    op.create_table(
        "order_tax_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("tax_rule_id", sa.Integer(), nullable=True),
        sa.Column("tax_name", sa.String(), nullable=False),
        sa.Column("tax_scope", sa.String(), nullable=False),
        sa.Column("tax_mode", sa.String(), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("taxable_base", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tax_rule_id"],
            ["tax_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_tax_lines", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_order_tax_lines_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_order_tax_lines_order_id"), ["order_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_order_tax_lines_tax_rule_id"), ["tax_rule_id"], unique=False
        )

    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("payment_method", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_payments_user_idempotency"
        ),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payments_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_payments_idempotency_key"), ["idempotency_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_payments_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "refunds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_refunds_user_idempotency"
        ),
    )
    with op.batch_alter_table("refunds", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_refunds_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_refunds_idempotency_key"), ["idempotency_key"], unique=False
        )

    op.create_table(
        "refund_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("refund_id", sa.Integer(), nullable=False),
        sa.Column("order_item_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["refund_id"],
            ["refunds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("refund_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_refund_items_id"), ["id"], unique=False)

    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("order_item_id", sa.Integer(), nullable=True),
        sa.Column("purchase_order_id", sa.Integer(), nullable=True),
        sa.Column("purchase_order_item_id", sa.Integer(), nullable=True),
        sa.Column("refund_id", sa.Integer(), nullable=True),
        sa.Column("movement_type", sa.String(), nullable=False),
        sa.Column("quantity_before", sa.Integer(), nullable=False),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("quantity_after", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_item_id"],
            ["purchase_order_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["refund_id"],
            ["refunds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stock_movements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stock_movements_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_stock_movements_movement_type"),
            ["movement_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_order_id"), ["order_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_order_item_id"),
            ["order_item_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_purchase_order_id"),
            ["purchase_order_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_purchase_order_item_id"),
            ["purchase_order_item_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_refund_id"), ["refund_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###
    _seed_rbac_defaults()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_movements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_movements_user_id"))
        batch_op.drop_index(batch_op.f("ix_stock_movements_refund_id"))
        batch_op.drop_index(batch_op.f("ix_stock_movements_purchase_order_item_id"))
        batch_op.drop_index(batch_op.f("ix_stock_movements_purchase_order_id"))
        batch_op.drop_index(batch_op.f("ix_stock_movements_product_id"))
        batch_op.drop_index(batch_op.f("ix_stock_movements_order_item_id"))
        batch_op.drop_index(batch_op.f("ix_stock_movements_order_id"))
        batch_op.drop_index(batch_op.f("ix_stock_movements_movement_type"))
        batch_op.drop_index(batch_op.f("ix_stock_movements_id"))

    op.drop_table("stock_movements")
    with op.batch_alter_table("refund_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refund_items_id"))

    op.drop_table("refund_items")
    with op.batch_alter_table("refunds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refunds_idempotency_key"))
        batch_op.drop_index(batch_op.f("ix_refunds_id"))

    op.drop_table("refunds")
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payments_user_id"))
        batch_op.drop_index(batch_op.f("ix_payments_idempotency_key"))
        batch_op.drop_index(batch_op.f("ix_payments_id"))

    op.drop_table("payments")
    with op.batch_alter_table("order_tax_lines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_tax_lines_tax_rule_id"))
        batch_op.drop_index(batch_op.f("ix_order_tax_lines_order_id"))
        batch_op.drop_index(batch_op.f("ix_order_tax_lines_id"))

    op.drop_table("order_tax_lines")
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_items_id"))

    op.drop_table("order_items")
    with op.batch_alter_table("loyalty_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_loyalty_transactions_transaction_type"))
        batch_op.drop_index(batch_op.f("ix_loyalty_transactions_order_id"))
        batch_op.drop_index(batch_op.f("ix_loyalty_transactions_id"))
        batch_op.drop_index(batch_op.f("ix_loyalty_transactions_customer_id"))

    op.drop_table("loyalty_transactions")
    with op.batch_alter_table("purchase_invoice_items", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_purchase_invoice_items_purchase_order_item_id")
        )
        batch_op.drop_index(batch_op.f("ix_purchase_invoice_items_product_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_invoice_items_invoice_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_invoice_items_id"))

    op.drop_table("purchase_invoice_items")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_reservation_status"))
        batch_op.drop_index(batch_op.f("ix_orders_reservation_expires_at"))
        batch_op.drop_index(batch_op.f("ix_orders_idempotency_key"))
        batch_op.drop_index(batch_op.f("ix_orders_id"))

    op.drop_table("orders")
    with op.batch_alter_table("tax_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tax_rules_tax_scope"))
        batch_op.drop_index(batch_op.f("ix_tax_rules_tax_mode"))
        batch_op.drop_index(batch_op.f("ix_tax_rules_product_id"))
        batch_op.drop_index(batch_op.f("ix_tax_rules_name"))
        batch_op.drop_index(batch_op.f("ix_tax_rules_is_active"))
        batch_op.drop_index(batch_op.f("ix_tax_rules_id"))
        batch_op.drop_index(batch_op.f("ix_tax_rules_category_id"))

    op.drop_table("tax_rules")
    with op.batch_alter_table("shift_reconciliations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shift_reconciliations_id"))
        batch_op.drop_index(batch_op.f("ix_shift_reconciliations_drawer_session_id"))
        batch_op.drop_index(batch_op.f("ix_shift_reconciliations_closed_by_user_id"))

    op.drop_table("shift_reconciliations")
    with op.batch_alter_table("purchase_order_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_order_items_purchase_order_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_order_items_product_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_order_items_id"))

    op.drop_table("purchase_order_items")
    with op.batch_alter_table("purchase_invoices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_invoices_user_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_invoices_supplier_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_invoices_status"))
        batch_op.drop_index(batch_op.f("ix_purchase_invoices_purchase_order_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_invoices_invoice_number"))
        batch_op.drop_index(batch_op.f("ix_purchase_invoices_id"))

    op.drop_table("purchase_invoices")
    with op.batch_alter_table("promotions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_promotions_id"))
        batch_op.drop_index(batch_op.f("ix_promotions_code"))

    op.drop_table("promotions")
    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_roles_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_roles_role_id"))
        batch_op.drop_index(batch_op.f("ix_user_roles_id"))

    op.drop_table("user_roles")
    with op.batch_alter_table("sync_event_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_event_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_sync_event_logs_status"))
        batch_op.drop_index(batch_op.f("ix_sync_event_logs_idempotency_key"))
        batch_op.drop_index(batch_op.f("ix_sync_event_logs_id"))
        batch_op.drop_index(batch_op.f("ix_sync_event_logs_event_type"))
        batch_op.drop_index(batch_op.f("ix_sync_event_logs_client_event_id"))

    op.drop_table("sync_event_logs")
    with op.batch_alter_table("role_permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_permissions_role_id"))
        batch_op.drop_index(batch_op.f("ix_role_permissions_permission_id"))
        batch_op.drop_index(batch_op.f("ix_role_permissions_id"))

    op.drop_table("role_permissions")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_token"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_id"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("purchase_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_orders_user_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_orders_supplier_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_orders_status"))
        batch_op.drop_index(batch_op.f("ix_purchase_orders_id"))

    op.drop_table("purchase_orders")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_sku"))
        batch_op.drop_index(batch_op.f("ix_products_name"))
        batch_op.drop_index(batch_op.f("ix_products_id"))

    op.drop_table("products")
    with op.batch_alter_table("drawer_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_drawer_sessions_id"))

    op.drop_table("drawer_sessions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_suppliers_name"))
        batch_op.drop_index(batch_op.f("ix_suppliers_id"))

    op.drop_table("suppliers")
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_name"))
        batch_op.drop_index(batch_op.f("ix_roles_id"))

    op.drop_table("roles")
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permissions_id"))
        batch_op.drop_index(batch_op.f("ix_permissions_code"))

    op.drop_table("permissions")
    with op.batch_alter_table("localization_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_localization_settings_id"))

    op.drop_table("localization_settings")
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customers_phone"))
        batch_op.drop_index(batch_op.f("ix_customers_name"))
        batch_op.drop_index(batch_op.f("ix_customers_id"))
        batch_op.drop_index(batch_op.f("ix_customers_email"))

    op.drop_table("customers")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_name"))
        batch_op.drop_index(batch_op.f("ix_categories_id"))

    op.drop_table("categories")
    # ### end Alembic commands ###
