/// Lightweight UI strings (en/id), resolved from the active region
/// language. The backend sends auth-error translations via Accept-Language;
/// this covers the client UI itself.
library;

import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'localization_controller.dart';

const Map<String, Map<String, String>> _translations = {
  'en': {
    'appTitle': 'OctoPOS',
    'signedInAs': 'Signed in as',
    'cashier': 'Cashier',
    'print': 'Print',
    'date': 'Date',
    'signIn': 'Sign in',
    'signOut': 'Sign out',
    'createAccount': 'Create account',
    'register': 'Register',
    'alreadyHaveAccount': 'Already have an account? Sign in',
    'newCashierRegister': 'New cashier? Register',
    'email': 'Email',
    'password': 'Password',
    'fullName': 'Full name',
    'validEmail': 'Valid email required',
    'minPassword': 'Min 8 characters',
    'accountLocked': 'Account temporarily locked. Try again later.',
    'sessionExpired': 'Your session has expired. Please sign in again.',
    'forbidden': 'You do not have permission to do that.',
    'notFound': 'The requested item was not found.',
    'conflict': 'A conflict occurred. Please refresh and try again.',
    'imageTooLarge': 'The image exceeds the 5 MB limit.',
    'unsupportedImage': 'Unsupported image type (use JPEG, PNG or WebP).',
    'validationFailed': 'Please check the entered values.',
    'rateLimited': 'Too many attempts. Please wait a moment and retry.',
    'genericError': 'Something went wrong. Please try again.',
    'badCredentials': 'Incorrect email or password.',
    'cannotReachServer': 'Could not reach the server. Is the backend running?',
    'required': 'Required',
    'back': 'Back',
    'create': 'Create',
    'pos': 'POS',
    'serving': 'Serving',
    'servingEmpty': 'No orders waiting to be served',
    'orderNumber': 'Order #{{id}}',
    'startPreparing': 'Start preparing',
    'markReady': 'Mark ready',
    'markServed': 'Mark served',
    'statusQueued': 'Queued',
    'statusPreparing': 'Preparing',
    'statusReady': 'Ready',
    'noSearchResults': 'No matches for “{{q}}”',
    'statusServed': 'Served',
    'tracking': 'Tracking',
    'trackingEmpty': 'No active trips being tracked',
    'statusAssigned': 'Assigned',
    'statusEnRoute': 'En route',
    'statusOnSite': 'On site',
    'startTrip': 'Start trip',
    'arrivedOnSite': 'I\'m on site',
    'useMyLocation': 'Use my location',
    'reportPosition': 'Report position',
    'destination': 'Destination',
    'serviceAddress': 'Service address (optional)',
    'products': 'Products',
    'customers': 'Customers',
    'editCustomer': 'Edit customer',
    'reports': 'Reports',
    'refunds': 'Refunds',
    'endShift': 'End shift',
    'openDrawer': 'Open drawer',
    'noOpenDrawer': 'No open drawer. Open one before taking orders.',
    'drawerOpen': 'Drawer #{{id}} open',
    'cart': 'Cart',
    'cartEmpty': 'Cart is empty',
    'cartCount': 'Cart ({{count}})',
    'customer': 'Customer',
    'guest': 'Guest',
    'walkInGuest': 'Walk-in guest',
    'selectCustomer': 'Select customer',
    'registerCustomer': 'Register new customer',
    'noCustomersFound': 'No customers found',
    'total': 'Total',
    'checkout': 'Checkout',
    'searchProducts': 'Search products…',
    'all': 'All',
    'inStock': '{{count}} in stock',
    'pay': 'Pay',
    'cash': 'Cash',
    'card': 'Card',
    'promotionCode': 'Promotion code',
    'cashReceived': 'Cash received',
    'pointsBalance': 'Points balance',
    'redeemPoints': 'Redeem points',
    'split': 'Split',
    'splitCash': 'Cash portion',
    'splitHint': 'Card pays {{card}}',
    'insufficientCash': 'Insufficient cash',
    'subtotal': 'Subtotal',
    'discount': 'Discount',
    'tax': 'Tax',
    'paid': 'Paid ({{method}})',
    'change': 'Change',
    'done': 'Done',
    'orderId': 'Order #{{id}}',
    'load': 'Load',
    'noCompletedOrders': 'No completed orders yet',
    'productId': 'Product #{{id}}',
    'refundTotal': 'Refund total: {{total}}',
    'refundSelected': 'Refund selected items',
    'selectAtLeastOne': 'Select at least one item to refund',
    'refundCreated': 'Refund created successfully',
    'salesSummary': 'Sales summary',
    'grossRevenue': 'Gross revenue',
    'discounts': 'Discounts',
    'netRevenue': 'Net revenue',
    'orders': 'Orders',
    'reprint': 'Reprint',
    'cancelOrder': 'Cancel order',
    'confirmCancel': 'Cancel this order? Stock will be restored.',
    'statusPending': 'Pending',
    'statusServing': 'Serving',
    'statusCompleted': 'Completed',
    'statusCancelled': 'Cancelled',
    'noOrders': 'No orders yet',
    'itemsCount': '{{count}} item(s)',
    'inventory': 'Inventory',
    'movements': 'Movements',
    'replenishment': 'Replenishment',
    'movementType': 'Movement type',
    'qtyBefore': 'Before',
    'qtyAfter': 'After',
    'adjustStock': 'Adjust stock',
    'adjustDelta': 'Quantity change (+/-)',
    'adjustNote': 'Note (optional)',
    'noMovements': 'No stock movements yet',
    'noSuggestions': 'All products above their reorder points',
    'recommendedQty': 'Suggested: {{qty}}',
    'purchasing': 'Purchasing',
    'suppliers': 'Suppliers',
    'newSupplier': 'New supplier',
    'editSupplier': 'Edit {{name}}',
    'noSuppliers': 'No suppliers yet',
    'supplierName': 'Supplier name',
    'supplierEmail': 'Contact email',
    'supplierPhone': 'Phone',
    'supplierAddress': 'Address',
    'contact': 'Contact',
    'purchaseOrders': 'Purchase orders',
    'newPurchaseOrder': 'New purchase order',
    'noPurchaseOrders': 'No purchase orders yet',
    'orderStatus': 'Status',
    'createOrder': 'Create order',
    'markOrdered': 'Mark ordered',
    'receiveItems': 'Receive items',
    'receive': 'Receive',
    'confirmMarkOrdered': 'Mark this purchase order as ordered?',
    'confirmCancelOrder': 'Cancel this purchase order?',
    'confirmReceiveItems':
        'Receiving updates stock and writes stock-movement ledger entries.',
    'qtyOrdered': 'Ordered',
    'qtyReceived': 'Received',
    'unitCost': 'Unit cost',
    'selectProduct': 'Select product',
    'estimatedTotal': 'Estimated total',
    'purchaseInvoices': 'Purchase invoices',
    'newInvoice': 'New invoice',
    'noInvoices': 'No purchase invoices yet',
    'invoiceNumber': 'Invoice number',
    'invoiceDate': 'Invoice date',
    'dueDate': 'Due date',
    'submitForReview': 'Submit for review',
    'approve': 'Approve',
    'reject': 'Reject',
    'reviewNote': 'Review note (optional)',
    'confirmApprove': 'Approve this invoice?',
    'confirmReject': 'Reject this invoice?',
    'quantityVariance': 'Qty variance',
    'priceVariance': 'Price variance',
    'billed': 'Billed',
    'createInvoice': 'Create invoice',
    'selectEligiblePo': 'Select a received purchase order',
    'noEligiblePo': 'No purchase orders with received items to invoice',
    'submitForReviewOrder': 'Submit for review',
    'confirmSubmitOrder': 'Submit this purchase order for review?',
    'confirmApproveOrder': 'Approve this purchase order?',
    'confirmRejectOrder': 'Reject this purchase order?',
    'pendingReview': 'Pending review',
    'supplierPayments': 'Supplier payments',
    'noPayments': 'No supplier payments yet',
    'createPayment': 'Create payment',
    'paymentAmount': 'Amount',
    'paymentMethod': 'Payment method',
    'paymentReference': 'Reference',
    'paymentDate': 'Payment date',
    'payCash': 'Cash',
    'payTransfer': 'Bank transfer',
    'payCard': 'Card',
    'payMobile': 'Mobile money',
    'confirmSubmitPayment': 'Submit this payment for review?',
    'confirmApprovePayment': 'Approve this payment?',
    'confirmRejectPayment': 'Reject this payment?',
    'selectApprovedInvoice': 'Select an approved invoice',
    'noApprovedInvoices': 'No approved invoices to pay yet',
    'taxRules': 'Tax rules',
    'newTaxRule': 'New tax rule',
    'editTaxRule': 'Edit tax rule',
    'noTaxRules': 'No tax rules yet',
    'taxName': 'Tax name',
    'taxRate': 'Rate',
    'taxScope': 'Applies to',
    'taxMode': 'Mode',
    'settings': 'Settings',
    'localizationSettings': 'Localization',
    'language': 'Language',
    'timezone': 'Timezone',
    'currency': 'Currency',
    'dateFormat': 'Date format',
    'numberFormat': 'Number format',
    'countryCode': 'Country',
    'settingsSaved': 'Settings saved',
    'period': 'Period',
    'periodToday': 'Today',
    'period7d': 'Last 7 days',
    'period30d': 'Last 30 days',
    'periodAll': 'All time',
    'topProducts': 'Top products',
    'salesByCategory': 'Sales by category',
    'shifts': 'Shifts',
    'todayClose': 'Today close',
    'shiftCount': 'Shifts: {{count}}',
    'operator': 'Cashier',
    'viewShiftReport': 'View report',
    'promotions': 'Promotions',
    'newPromotion': 'New promotion',
    'editPromotion': 'Edit promotion',
    'discountType': 'Discount type',
    'percentage': 'Percentage',
    'fixed': 'Fixed amount',
    'discountValue': 'Discount value',
    'minOrder': 'Min order amount',
    'maxDiscount': 'Max discount',
    'appliesTo': 'Applies to',
    'usage': 'Used {{count}}/{{limit}}',
    'usageUnlimited': 'Used {{count}} times',
    'deactivate': 'Deactivate',
    'confirmDeactivate':
        'Deactivate this promotion? It stops applying immediately.',
    'noPromotions': 'No promotions yet',
    'isActive': 'Active',
    'description': 'Description',
    'usageLimit': 'Usage limit',
    'admin': 'Admin',
    'auditLog': 'Audit log',
    'roles': 'Roles',
    'newRole': 'New role',
    'editRole': 'Edit role',
    'roleName': 'Role name',
    'permissions': 'Permissions',
    'assignRoles': 'Assign roles',
    'noAuditEntries': 'No audit entries',
    'systemRole': 'System',
    'action': 'Action',
    'staff': 'Staff',
    'newStaff': 'New staff',
    'editStaff': 'Edit {{name}}',
    'noStaff': 'No staff yet. Add your first team member.',
    'staffEmail': 'Email',
    'staffFullName': 'Full name',
    'staffPassword': 'Password',
    'staffPasswordHint': 'Min 8 characters, letters and digits',
    'resetPassword': 'Reset password',
    'resetPasswordHint': 'Leave blank to keep the current password',
    'staffActive': 'Active',
    'staffInactive': 'Inactive',
    'staffRoles': 'Roles: {{roles}}',
    'confirmDeactivateStaff':
        'Deactivate {{name}}? They can no longer sign in.',
    'staffCreated': 'Staff created',
    'staffUpdated': 'Staff updated',
    'selfDeactivateBlocked': 'You cannot deactivate your own account',
    'avgOrder': 'Avg order',
    'lowStock': 'Low stock',
    'healthyStock': 'All product stock levels are healthy.',
    'countedCash': 'Counted cash',
    'countedNonCash': 'Counted non-cash (optional)',
    'reconcileClose': 'Reconcile & close drawer',
    'shiftReconciled': 'Shift reconciled',
    'cashSales': 'Cash sales',
    'nonCashSales': 'Non-cash sales',
    'expectedCash': 'Expected cash',
    'variance': 'Variance',
    'newProduct': 'New product',
    'uploadPhoto': 'Upload photo',
    'removePhoto': 'Remove photo',
    'categories': 'Categories',
    'chooseColor': 'Pick a color',
    'noColor': 'No color',
    'editProduct': 'Edit {{name}}',
    'name': 'Name',
    'sku': 'SKU',
    'price': 'Price',
    'stock': 'Stock',
    'category': 'Category',
    'save': 'Save',
    'cancel': 'Cancel',
    'no': 'No',
    'yes': 'Yes',
    'newCustomer': 'New customer',
    'phone': 'Phone',
    'region': 'Region',
    'regionDefault': 'Default (follow store settings)',
    'toggleTheme': 'Toggle theme',
  },
  'id': {
    'appTitle': 'OctoPOS',
    'signedInAs': 'Masuk sebagai',
    'cashier': 'Kasir',
    'print': 'Cetak',
    'date': 'Tanggal',
    'signIn': 'Masuk',
    'signOut': 'Keluar',
    'createAccount': 'Buat akun',
    'register': 'Daftar',
    'alreadyHaveAccount': 'Sudah punya akun? Masuk',
    'newCashierRegister': 'Kasir baru? Daftar',
    'email': 'Email',
    'password': 'Kata sandi',
    'fullName': 'Nama lengkap',
    'validEmail': 'Email valid diperlukan',
    'minPassword': 'Min. 8 karakter',
    'accountLocked': 'Akun terkunci sementara. Coba lagi nanti.',
    'sessionExpired': 'Sesi Anda berakhir. Silakan masuk kembali.',
    'forbidden': 'Anda tidak memiliki izin untuk melakukan itu.',
    'notFound': 'Item yang diminta tidak ditemukan.',
    'conflict': 'Terjadi konflik. Silakan muat ulang dan coba lagi.',
    'imageTooLarge': 'Gambar melebihi batas 5 MB.',
    'unsupportedImage':
        'Jenis gambar tidak didukung (gunakan JPEG, PNG, atau WebP).',
    'validationFailed': 'Periksa kembali nilai yang dimasukkan.',
    'rateLimited': 'Terlalu banyak percobaan. Tunggu sebentar lalu coba lagi.',
    'genericError': 'Terjadi kesalahan. Silakan coba lagi.',
    'badCredentials': 'Email atau kata sandi salah.',
    'cannotReachServer':
        'Tidak dapat menghubungi server. Apakah backend berjalan?',
    'required': 'Wajib diisi',
    'back': 'Kembali',
    'create': 'Buat',
    'pos': 'POS',
    'serving': 'Pelayanan',
    'servingEmpty': 'Belum ada pesanan yang menunggu disajikan',
    'orderNumber': 'Pesanan #{{id}}',
    'startPreparing': 'Mulai menyiapkan',
    'markReady': 'Tandai siap',
    'markServed': 'Tandai disajikan',
    'statusQueued': 'Antre',
    'statusPreparing': 'Disiapkan',
    'statusReady': 'Siap',
    'noSearchResults': 'Tidak ada hasil untuk “{{q}}”',
    'statusServed': 'Disajikan',
    'tracking': 'Pelacakan',
    'trackingEmpty': 'Belum ada perjalanan yang dilacak',
    'statusAssigned': 'Ditugaskan',
    'statusEnRoute': 'Dalam perjalanan',
    'statusOnSite': 'Di lokasi',
    'startTrip': 'Mulai perjalanan',
    'arrivedOnSite': 'Sudah di lokasi',
    'useMyLocation': 'Gunakan lokasi saya',
    'reportPosition': 'Laporkan posisi',
    'destination': 'Tujuan',
    'serviceAddress': 'Alamat layanan (opsional)',
    'products': 'Produk',
    'customers': 'Pelanggan',
    'editCustomer': 'Edit pelanggan',
    'reports': 'Laporan',
    'refunds': 'Pengembalian',
    'endShift': 'Akhiri shift',
    'openDrawer': 'Buka laci',
    'noOpenDrawer':
        'Tidak ada laci terbuka. Buka laci sebelum menerima pesanan.',
    'drawerOpen': 'Laci #{{id}} terbuka',
    'cart': 'Keranjang',
    'cartEmpty': 'Keranjang kosong',
    'cartCount': 'Keranjang ({{count}})',
    'customer': 'Pelanggan',
    'guest': 'Tamu',
    'walkInGuest': 'Tamu tanpa daftar',
    'selectCustomer': 'Pilih pelanggan',
    'registerCustomer': 'Daftarkan pelanggan baru',
    'noCustomersFound': 'Tidak ada pelanggan ditemukan',
    'total': 'Total',
    'checkout': 'Bayar',
    'searchProducts': 'Cari produk…',
    'all': 'Semua',
    'inStock': 'Stok {{count}}',
    'pay': 'Bayar',
    'cash': 'Tunai',
    'card': 'Kartu',
    'promotionCode': 'Kode promosi',
    'cashReceived': 'Uang diterima',
    'pointsBalance': 'Saldo poin',
    'redeemPoints': 'Tukarkan poin',
    'split': 'Split',
    'splitCash': 'Bagian tunai',
    'splitHint': 'Kartu membayar {{card}}',
    'insufficientCash': 'Uang tidak cukup',
    'subtotal': 'Subtotal',
    'discount': 'Diskon',
    'tax': 'Pajak',
    'paid': 'Dibayar ({{method}})',
    'change': 'Kembalian',
    'done': 'Selesai',
    'orderId': 'Pesanan #{{id}}',
    'load': 'Muat',
    'noCompletedOrders': 'Belum ada pesanan selesai',
    'productId': 'Produk #{{id}}',
    'refundTotal': 'Total refund: {{total}}',
    'refundSelected': 'Refund item terpilih',
    'selectAtLeastOne': 'Pilih minimal satu item untuk direfund',
    'refundCreated': 'Refund berhasil dibuat',
    'salesSummary': 'Ringkasan penjualan',
    'grossRevenue': 'Pendapatan kotor',
    'discounts': 'Diskon',
    'netRevenue': 'Pendapatan bersih',
    'orders': 'Pesanan',
    'reprint': 'Cetak ulang',
    'cancelOrder': 'Batalkan pesanan',
    'confirmCancel': 'Batalkan pesanan ini? Stok akan dikembalikan.',
    'statusPending': 'Menunggu',
    'statusServing': 'Dalam pelayanan',
    'statusCompleted': 'Selesai',
    'statusCancelled': 'Dibatalkan',
    'noOrders': 'Belum ada pesanan',
    'itemsCount': '{{count}} item',
    'inventory': 'Inventaris',
    'movements': 'Riwayat stok',
    'replenishment': 'Pengisian stok',
    'movementType': 'Jenis pergerakan',
    'qtyBefore': 'Sebelum',
    'qtyAfter': 'Sesudah',
    'adjustStock': 'Sesuaikan stok',
    'adjustDelta': 'Perubahan jumlah (+/-)',
    'adjustNote': 'Catatan (opsional)',
    'noMovements': 'Belum ada pergerakan stok',
    'noSuggestions': 'Semua produk di atas titik pemesanan ulang',
    'recommendedQty': 'Disarankan: {{qty}}',
    'purchasing': 'Pembelian',
    'suppliers': 'Pemasok',
    'newSupplier': 'Pemasok baru',
    'editSupplier': 'Edit {{name}}',
    'noSuppliers': 'Belum ada pemasok',
    'supplierName': 'Nama pemasok',
    'supplierEmail': 'Email kontak',
    'supplierPhone': 'Telepon',
    'supplierAddress': 'Alamat',
    'contact': 'Kontak',
    'purchaseOrders': 'Pesanan pembelian',
    'newPurchaseOrder': 'Pesanan pembelian baru',
    'noPurchaseOrders': 'Belum ada pesanan pembelian',
    'orderStatus': 'Status',
    'createOrder': 'Buat pesanan',
    'markOrdered': 'Tandai dipesan',
    'receiveItems': 'Terima barang',
    'receive': 'Terima',
    'confirmMarkOrdered': 'Tandai pesanan pembelian ini sebagai dipesan?',
    'confirmCancelOrder': 'Batalkan pesanan pembelian ini?',
    'confirmReceiveItems':
        'Menerima barang memperbarui stok dan mencatat riwayat pergerakan stok.',
    'qtyOrdered': 'Dipesan',
    'qtyReceived': 'Diterima',
    'unitCost': 'Biaya satuan',
    'selectProduct': 'Pilih produk',
    'estimatedTotal': 'Perkiraan total',
    'purchaseInvoices': 'Faktur pembelian',
    'newInvoice': 'Faktur baru',
    'noInvoices': 'Belum ada faktur pembelian',
    'invoiceNumber': 'Nomor faktur',
    'invoiceDate': 'Tanggal faktur',
    'dueDate': 'Tanggal jatuh tempo',
    'submitForReview': 'Kirim untuk ditinjau',
    'approve': 'Setujui',
    'reject': 'Tolak',
    'reviewNote': 'Catatan tinjauan (opsional)',
    'confirmApprove': 'Setujui faktur ini?',
    'confirmReject': 'Tolak faktur ini?',
    'quantityVariance': 'Selisih qty',
    'priceVariance': 'Selisih harga',
    'billed': 'Ditagih',
    'createInvoice': 'Buat faktur',
    'selectEligiblePo': 'Pilih pesanan pembelian yang sudah diterima',
    'noEligiblePo': 'Tidak ada pesanan pembelian dengan barang diterima untuk ditagih',
    'submitForReviewOrder': 'Kirim untuk ditinjau',
    'confirmSubmitOrder': 'Kirim pesanan pembelian ini untuk ditinjau?',
    'confirmApproveOrder': 'Setujui pesanan pembelian ini?',
    'confirmRejectOrder': 'Tolak pesanan pembelian ini?',
    'pendingReview': 'Menunggu tinjauan',
    'supplierPayments': 'Pembayaran pemasok',
    'noPayments': 'Belum ada pembayaran pemasok',
    'createPayment': 'Buat pembayaran',
    'paymentAmount': 'Jumlah',
    'paymentMethod': 'Metode pembayaran',
    'paymentReference': 'Referensi',
    'paymentDate': 'Tanggal pembayaran',
    'payCash': 'Tunai',
    'payTransfer': 'Transfer bank',
    'payCard': 'Kartu',
    'payMobile': 'Uang elektronik',
    'confirmSubmitPayment': 'Kirim pembayaran ini untuk ditinjau?',
    'confirmApprovePayment': 'Setujui pembayaran ini?',
    'confirmRejectPayment': 'Tolak pembayaran ini?',
    'selectApprovedInvoice': 'Pilih faktur yang disetujui',
    'noApprovedInvoices': 'Belum ada faktur disetujui untuk dibayar',
    'taxRules': 'Aturan pajak',
    'newTaxRule': 'Aturan pajak baru',
    'editTaxRule': 'Edit aturan pajak',
    'noTaxRules': 'Belum ada aturan pajak',
    'taxName': 'Nama pajak',
    'taxRate': 'Tarif',
    'taxScope': 'Berlaku untuk',
    'taxMode': 'Mode',
    'settings': 'Pengaturan',
    'localizationSettings': 'Lokalisasi',
    'language': 'Bahasa',
    'timezone': 'Zona waktu',
    'currency': 'Mata uang',
    'dateFormat': 'Format tanggal',
    'numberFormat': 'Format angka',
    'countryCode': 'Negara',
    'settingsSaved': 'Pengaturan disimpan',
    'period': 'Periode',
    'periodToday': 'Hari ini',
    'period7d': '7 hari terakhir',
    'period30d': '30 hari terakhir',
    'periodAll': 'Semua waktu',
    'topProducts': 'Produk terlaris',
    'salesByCategory': 'Penjualan per kategori',
    'shifts': 'Shift',
    'todayClose': 'Penutupan hari ini',
    'shiftCount': 'Shift: {{count}}',
    'operator': 'Kasir',
    'viewShiftReport': 'Lihat laporan',
    'promotions': 'Promosi',
    'newPromotion': 'Promosi baru',
    'editPromotion': 'Edit promosi',
    'discountType': 'Jenis diskon',
    'percentage': 'Persentase',
    'fixed': 'Jumlah tetap',
    'discountValue': 'Nilai diskon',
    'minOrder': 'Min. pesanan',
    'maxDiscount': 'Maks. diskon',
    'appliesTo': 'Berlaku untuk',
    'usage': 'Digunakan {{count}}/{{limit}}',
    'usageUnlimited': 'Digunakan {{count}} kali',
    'deactivate': 'Nonaktifkan',
    'confirmDeactivate': 'Nonaktifkan promosi ini? Berlaku berhenti segera.',
    'noPromotions': 'Belum ada promosi',
    'isActive': 'Aktif',
    'description': 'Deskripsi',
    'usageLimit': 'Batas pemakaian',
    'admin': 'Admin',
    'auditLog': 'Log audit',
    'roles': 'Peran',
    'newRole': 'Peran baru',
    'editRole': 'Edit peran',
    'roleName': 'Nama peran',
    'permissions': 'Izin',
    'assignRoles': 'Tetapkan peran',
    'noAuditEntries': 'Tidak ada entri audit',
    'systemRole': 'Sistem',
    'action': 'Aksi',
    'staff': 'Staf',
    'newStaff': 'Staf baru',
    'editStaff': 'Edit {{name}}',
    'noStaff': 'Belum ada staf. Tambahkan anggota tim pertama Anda.',
    'staffEmail': 'Email',
    'staffFullName': 'Nama lengkap',
    'staffPassword': 'Kata sandi',
    'staffPasswordHint': 'Min. 8 karakter, huruf dan angka',
    'resetPassword': 'Atur ulang kata sandi',
    'resetPasswordHint': 'Kosongkan untuk mempertahankan kata sandi saat ini',
    'staffActive': 'Aktif',
    'staffInactive': 'Nonaktif',
    'staffRoles': 'Peran: {{roles}}',
    'confirmDeactivateStaff':
        'Nonaktifkan {{name}}? Mereka tidak dapat masuk lagi.',
    'staffCreated': 'Staf dibuat',
    'staffUpdated': 'Staf diperbarui',
    'selfDeactivateBlocked': 'Anda tidak dapat menonaktifkan akun sendiri',
    'avgOrder': 'Rata-rata pesanan',
    'lowStock': 'Stok menipis',
    'healthyStock': 'Semua stok produk sehat.',
    'countedCash': 'Tunai dihitung',
    'countedNonCash': 'Non-tunai dihitung (opsional)',
    'reconcileClose': 'Rekonsiliasi & tutup laci',
    'shiftReconciled': 'Shift selesai direkonsiliasi',
    'cashSales': 'Penjualan tunai',
    'nonCashSales': 'Penjualan non-tunai',
    'expectedCash': 'Tunai diperkirakan',
    'variance': 'Selisih',
    'newProduct': 'Produk baru',
    'uploadPhoto': 'Unggah foto',
    'removePhoto': 'Hapus foto',
    'categories': 'Kategori',
    'chooseColor': 'Pilih warna',
    'noColor': 'Tanpa warna',
    'editProduct': 'Edit {{name}}',
    'name': 'Nama',
    'sku': 'SKU',
    'price': 'Harga',
    'stock': 'Stok',
    'category': 'Kategori',
    'save': 'Simpan',
    'cancel': 'Batal',
    'no': 'Tidak',
    'yes': 'Ya',
    'newCustomer': 'Pelanggan baru',
    'phone': 'Telepon',
    'region': 'Region',
    'regionDefault': 'Bawaan (ikuti pengaturan toko)',
    'toggleTheme': 'Ganti tema',
  },
};

class AppStrings {
  const AppStrings(this._strings);

  final Map<String, String> _strings;

  String of(String key, {Map<String, Object> args = const {}}) {
    var text = _strings[key] ?? _translations['en']![key] ?? key;
    for (final entry in args.entries) {
      text = text.replaceAll('{{${entry.key}}}', entry.value.toString());
    }
    return text;
  }
}

final stringsProvider = Provider<AppStrings>((ref) {
  final language = ref.watch(localizationControllerProvider).language;
  return AppStrings(_translations[language] ?? _translations['en']!);
});
