/// Lightweight UI strings (en/id), resolved from the active region
/// language. The backend sends auth-error translations via Accept-Language;
/// this covers the client UI itself.
library;

import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'localization_controller.dart';

const Map<String, Map<String, String>> _translations = {
  'en': {
    'appTitle': 'OctoPOS',
    'signedInAs': 'Signed in as',
    'cashier': 'Cashier',
    'print': 'Print',
    'date': 'Date',
    'signIn': 'Sign in',
    'signOut': 'Sign out',
    'createAccount': 'Create account',
    'register': 'Register',
    'alreadyHaveAccount': 'Already have an account? Sign in',
    'newCashierRegister': 'New cashier? Register',
    'email': 'Email',
    'password': 'Password',
    'fullName': 'Full name',
    'validEmail': 'Valid email required',
    'minPassword': 'Min 8 characters',
    'accountLocked': 'Account temporarily locked. Try again later.',
    'sessionExpired': 'Your session has expired. Please sign in again.',
    'forbidden': 'You do not have permission to do that.',
    'notFound': 'The requested item was not found.',
    'conflict': 'A conflict occurred. Please refresh and try again.',
    'imageTooLarge': 'The image exceeds the 5 MB limit.',
    'unsupportedImage': 'Unsupported image type (use JPEG, PNG or WebP).',
    'validationFailed': 'Please check the entered values.',
    'rateLimited': 'Too many attempts. Please wait a moment and retry.',
    'genericError': 'Something went wrong. Please try again.',
    'badCredentials': 'Incorrect email or password.',
    'cannotReachServer': 'Could not reach the server. Is the backend running?',
    'required': 'Required',
    'back': 'Back',
    'create': 'Create',
    'pos': 'POS',
    'products': 'Products',
    'customers': 'Customers',
    'reports': 'Reports',
    'refunds': 'Refunds',
    'endShift': 'End shift',
    'openDrawer': 'Open drawer',
    'noOpenDrawer': 'No open drawer. Open one before taking orders.',
    'drawerOpen': 'Drawer #{{id}} open',
    'cart': 'Cart',
    'cartEmpty': 'Cart is empty',
    'cartCount': 'Cart ({{count}})',
    'customer': 'Customer',
    'guest': 'Guest',
    'walkInGuest': 'Walk-in guest',
    'selectCustomer': 'Select customer',
    'registerCustomer': 'Register new customer',
    'noCustomersFound': 'No customers found',
    'total': 'Total',
    'checkout': 'Checkout',
    'searchProducts': 'Search products…',
    'all': 'All',
    'inStock': '{{count}} in stock',
    'pay': 'Pay',
    'cash': 'Cash',
    'card': 'Card',
    'promotionCode': 'Promotion code',
    'cashReceived': 'Cash received',
    'pointsBalance': 'Points balance',
    'redeemPoints': 'Redeem points',
    'split': 'Split',
    'splitCash': 'Cash portion',
    'splitHint': 'Card pays {{card}}',
    'insufficientCash': 'Insufficient cash',
    'subtotal': 'Subtotal',
    'discount': 'Discount',
    'tax': 'Tax',
    'paid': 'Paid ({{method}})',
    'change': 'Change',
    'done': 'Done',
    'orderId': 'Order #{{id}}',
    'load': 'Load',
    'noCompletedOrders': 'No completed orders yet',
    'productId': 'Product #{{id}}',
    'refundTotal': 'Refund total: {{total}}',
    'refundSelected': 'Refund selected items',
    'selectAtLeastOne': 'Select at least one item to refund',
    'refundCreated': 'Refund created successfully',
    'salesSummary': 'Sales summary',
    'grossRevenue': 'Gross revenue',
    'discounts': 'Discounts',
    'netRevenue': 'Net revenue',
    'orders': 'Orders',
    'reprint': 'Reprint',
    'cancelOrder': 'Cancel order',
    'confirmCancel': 'Cancel this order? Stock will be restored.',
    'statusPending': 'Pending',
    'statusCompleted': 'Completed',
    'statusCancelled': 'Cancelled',
    'noOrders': 'No orders yet',
    'itemsCount': '{{count}} item(s)',
    'inventory': 'Inventory',
    'movements': 'Movements',
    'replenishment': 'Replenishment',
    'movementType': 'Movement type',
    'qtyBefore': 'Before',
    'qtyAfter': 'After',
    'adjustStock': 'Adjust stock',
    'adjustDelta': 'Quantity change (+/-)',
    'adjustNote': 'Note (optional)',
    'noMovements': 'No stock movements yet',
    'noSuggestions': 'All products above their reorder points',
    'recommendedQty': 'Suggested: {{qty}}',
    'shifts': 'Shifts',
    'todayClose': 'Today close',
    'shiftCount': 'Shifts: {{count}}',
    'operator': 'Cashier',
    'viewShiftReport': 'View report',
    'promotions': 'Promotions',
    'newPromotion': 'New promotion',
    'editPromotion': 'Edit promotion',
    'discountType': 'Discount type',
    'percentage': 'Percentage',
    'fixed': 'Fixed amount',
    'discountValue': 'Discount value',
    'minOrder': 'Min order amount',
    'maxDiscount': 'Max discount',
    'appliesTo': 'Applies to',
    'usage': 'Used {{count}}/{{limit}}',
    'usageUnlimited': 'Used {{count}} times',
    'deactivate': 'Deactivate',
    'confirmDeactivate':
        'Deactivate this promotion? It stops applying immediately.',
    'noPromotions': 'No promotions yet',
    'isActive': 'Active',
    'description': 'Description',
    'usageLimit': 'Usage limit',
    'admin': 'Admin',
    'auditLog': 'Audit log',
    'roles': 'Roles',
    'newRole': 'New role',
    'editRole': 'Edit role',
    'roleName': 'Role name',
    'permissions': 'Permissions',
    'assignRoles': 'Assign roles',
    'noAuditEntries': 'No audit entries',
    'systemRole': 'System',
    'action': 'Action',
    'avgOrder': 'Avg order',
    'lowStock': 'Low stock',
    'healthyStock': 'All product stock levels are healthy.',
    'countedCash': 'Counted cash',
    'countedNonCash': 'Counted non-cash (optional)',
    'reconcileClose': 'Reconcile & close drawer',
    'shiftReconciled': 'Shift reconciled',
    'cashSales': 'Cash sales',
    'nonCashSales': 'Non-cash sales',
    'expectedCash': 'Expected cash',
    'variance': 'Variance',
    'newProduct': 'New product',
    'uploadPhoto': 'Upload photo',
    'removePhoto': 'Remove photo',
    'categories': 'Categories',
    'chooseColor': 'Pick a color',
    'noColor': 'No color',
    'editProduct': 'Edit {{name}}',
    'name': 'Name',
    'sku': 'SKU',
    'price': 'Price',
    'stock': 'Stock',
    'category': 'Category',
    'save': 'Save',
    'cancel': 'Cancel',
    'newCustomer': 'New customer',
    'phone': 'Phone',
    'region': 'Region',
    'regionDefault': 'Default (follow store settings)',
    'toggleTheme': 'Toggle theme',
  },
  'id': {
    'appTitle': 'OctoPOS',
    'signedInAs': 'Masuk sebagai',
    'cashier': 'Kasir',
    'print': 'Cetak',
    'date': 'Tanggal',
    'signIn': 'Masuk',
    'signOut': 'Keluar',
    'createAccount': 'Buat akun',
    'register': 'Daftar',
    'alreadyHaveAccount': 'Sudah punya akun? Masuk',
    'newCashierRegister': 'Kasir baru? Daftar',
    'email': 'Email',
    'password': 'Kata sandi',
    'fullName': 'Nama lengkap',
    'validEmail': 'Email valid diperlukan',
    'minPassword': 'Min. 8 karakter',
    'accountLocked': 'Akun terkunci sementara. Coba lagi nanti.',
    'sessionExpired': 'Sesi Anda berakhir. Silakan masuk kembali.',
    'forbidden': 'Anda tidak memiliki izin untuk melakukan itu.',
    'notFound': 'Item yang diminta tidak ditemukan.',
    'conflict': 'Terjadi konflik. Silakan muat ulang dan coba lagi.',
    'imageTooLarge': 'Gambar melebihi batas 5 MB.',
    'unsupportedImage':
        'Jenis gambar tidak didukung (gunakan JPEG, PNG, atau WebP).',
    'validationFailed': 'Periksa kembali nilai yang dimasukkan.',
    'rateLimited': 'Terlalu banyak percobaan. Tunggu sebentar lalu coba lagi.',
    'genericError': 'Terjadi kesalahan. Silakan coba lagi.',
    'badCredentials': 'Email atau kata sandi salah.',
    'cannotReachServer':
        'Tidak dapat menghubungi server. Apakah backend berjalan?',
    'required': 'Wajib diisi',
    'back': 'Kembali',
    'create': 'Buat',
    'pos': 'POS',
    'products': 'Produk',
    'customers': 'Pelanggan',
    'reports': 'Laporan',
    'refunds': 'Pengembalian',
    'endShift': 'Akhiri shift',
    'openDrawer': 'Buka laci',
    'noOpenDrawer':
        'Tidak ada laci terbuka. Buka laci sebelum menerima pesanan.',
    'drawerOpen': 'Laci #{{id}} terbuka',
    'cart': 'Keranjang',
    'cartEmpty': 'Keranjang kosong',
    'cartCount': 'Keranjang ({{count}})',
    'customer': 'Pelanggan',
    'guest': 'Tamu',
    'walkInGuest': 'Tamu tanpa daftar',
    'selectCustomer': 'Pilih pelanggan',
    'registerCustomer': 'Daftarkan pelanggan baru',
    'noCustomersFound': 'Tidak ada pelanggan ditemukan',
    'total': 'Total',
    'checkout': 'Bayar',
    'searchProducts': 'Cari produk…',
    'all': 'Semua',
    'inStock': 'Stok {{count}}',
    'pay': 'Bayar',
    'cash': 'Tunai',
    'card': 'Kartu',
    'promotionCode': 'Kode promosi',
    'cashReceived': 'Uang diterima',
    'pointsBalance': 'Saldo poin',
    'redeemPoints': 'Tukarkan poin',
    'split': 'Split',
    'splitCash': 'Bagian tunai',
    'splitHint': 'Kartu membayar {{card}}',
    'insufficientCash': 'Uang tidak cukup',
    'subtotal': 'Subtotal',
    'discount': 'Diskon',
    'tax': 'Pajak',
    'paid': 'Dibayar ({{method}})',
    'change': 'Kembalian',
    'done': 'Selesai',
    'orderId': 'Pesanan #{{id}}',
    'load': 'Muat',
    'noCompletedOrders': 'Belum ada pesanan selesai',
    'productId': 'Produk #{{id}}',
    'refundTotal': 'Total refund: {{total}}',
    'refundSelected': 'Refund item terpilih',
    'selectAtLeastOne': 'Pilih minimal satu item untuk direfund',
    'refundCreated': 'Refund berhasil dibuat',
    'salesSummary': 'Ringkasan penjualan',
    'grossRevenue': 'Pendapatan kotor',
    'discounts': 'Diskon',
    'netRevenue': 'Pendapatan bersih',
    'orders': 'Pesanan',
    'reprint': 'Cetak ulang',
    'cancelOrder': 'Batalkan pesanan',
    'confirmCancel': 'Batalkan pesanan ini? Stok akan dikembalikan.',
    'statusPending': 'Menunggu',
    'statusCompleted': 'Selesai',
    'statusCancelled': 'Dibatalkan',
    'noOrders': 'Belum ada pesanan',
    'itemsCount': '{{count}} item',
    'inventory': 'Inventaris',
    'movements': 'Riwayat stok',
    'replenishment': 'Pengisian stok',
    'movementType': 'Jenis pergerakan',
    'qtyBefore': 'Sebelum',
    'qtyAfter': 'Sesudah',
    'adjustStock': 'Sesuaikan stok',
    'adjustDelta': 'Perubahan jumlah (+/-)',
    'adjustNote': 'Catatan (opsional)',
    'noMovements': 'Belum ada pergerakan stok',
    'noSuggestions': 'Semua produk di atas titik pemesanan ulang',
    'recommendedQty': 'Disarankan: {{qty}}',
    'shifts': 'Shift',
    'todayClose': 'Penutupan hari ini',
    'shiftCount': 'Shift: {{count}}',
    'operator': 'Kasir',
    'viewShiftReport': 'Lihat laporan',
    'promotions': 'Promosi',
    'newPromotion': 'Promosi baru',
    'editPromotion': 'Edit promosi',
    'discountType': 'Jenis diskon',
    'percentage': 'Persentase',
    'fixed': 'Jumlah tetap',
    'discountValue': 'Nilai diskon',
    'minOrder': 'Min. pesanan',
    'maxDiscount': 'Maks. diskon',
    'appliesTo': 'Berlaku untuk',
    'usage': 'Digunakan {{count}}/{{limit}}',
    'usageUnlimited': 'Digunakan {{count}} kali',
    'deactivate': 'Nonaktifkan',
    'confirmDeactivate': 'Nonaktifkan promosi ini? Berlaku berhenti segera.',
    'noPromotions': 'Belum ada promosi',
    'isActive': 'Aktif',
    'description': 'Deskripsi',
    'usageLimit': 'Batas pemakaian',
    'admin': 'Admin',
    'auditLog': 'Log audit',
    'roles': 'Peran',
    'newRole': 'Peran baru',
    'editRole': 'Edit peran',
    'roleName': 'Nama peran',
    'permissions': 'Izin',
    'assignRoles': 'Tetapkan peran',
    'noAuditEntries': 'Tidak ada entri audit',
    'systemRole': 'Sistem',
    'action': 'Aksi',
    'avgOrder': 'Rata-rata pesanan',
    'lowStock': 'Stok menipis',
    'healthyStock': 'Semua stok produk sehat.',
    'countedCash': 'Tunai dihitung',
    'countedNonCash': 'Non-tunai dihitung (opsional)',
    'reconcileClose': 'Rekonsiliasi & tutup laci',
    'shiftReconciled': 'Shift selesai direkonsiliasi',
    'cashSales': 'Penjualan tunai',
    'nonCashSales': 'Penjualan non-tunai',
    'expectedCash': 'Tunai diperkirakan',
    'variance': 'Selisih',
    'newProduct': 'Produk baru',
    'uploadPhoto': 'Unggah foto',
    'removePhoto': 'Hapus foto',
    'categories': 'Kategori',
    'chooseColor': 'Pilih warna',
    'noColor': 'Tanpa warna',
    'editProduct': 'Edit {{name}}',
    'name': 'Nama',
    'sku': 'SKU',
    'price': 'Harga',
    'stock': 'Stok',
    'category': 'Kategori',
    'save': 'Simpan',
    'cancel': 'Batal',
    'newCustomer': 'Pelanggan baru',
    'phone': 'Telepon',
    'region': 'Region',
    'regionDefault': 'Bawaan (ikuti pengaturan toko)',
    'toggleTheme': 'Ganti tema',
  },
};

class AppStrings {
  const AppStrings(this._strings);

  final Map<String, String> _strings;

  String of(String key, {Map<String, Object> args = const {}}) {
    var text = _strings[key] ?? _translations['en']![key] ?? key;
    for (final entry in args.entries) {
      text = text.replaceAll('{{${entry.key}}}', entry.value.toString());
    }
    return text;
  }
}

final stringsProvider = Provider<AppStrings>((ref) {
  final language = ref.watch(localizationControllerProvider).language;
  return AppStrings(_translations[language] ?? _translations['en']!);
});
