/// Lightweight UI strings (en/id), resolved from the active region
/// language. The backend sends auth-error translations via Accept-Language;
/// this covers the client UI itself.
library;

import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'localization_controller.dart';

const Map<String, Map<String, String>> _translations = {
  'en': {
    'appTitle': 'OctoPOS',
    'signIn': 'Sign in',
    'signOut': 'Sign out',
    'createAccount': 'Create account',
    'register': 'Register',
    'alreadyHaveAccount': 'Already have an account? Sign in',
    'newCashierRegister': 'New cashier? Register',
    'email': 'Email',
    'password': 'Password',
    'fullName': 'Full name',
    'validEmail': 'Valid email required',
    'minPassword': 'Min 8 characters',
    'accountLocked': 'Account temporarily locked. Try again later.',
    'badCredentials': 'Incorrect email or password.',
    'cannotReachServer': 'Could not reach the server. Is the backend running?',
    'required': 'Required',
    'back': 'Back',
    'create': 'Create',
    'pos': 'POS',
    'products': 'Products',
    'customers': 'Customers',
    'reports': 'Reports',
    'refunds': 'Refunds',
    'endShift': 'End shift',
    'openDrawer': 'Open drawer',
    'noOpenDrawer': 'No open drawer. Open one before taking orders.',
    'drawerOpen': 'Drawer #{{id}} open',
    'cart': 'Cart',
    'cartEmpty': 'Cart is empty',
    'cartCount': 'Cart ({{count}})',
    'customer': 'Customer',
    'guest': 'Guest',
    'walkInGuest': 'Walk-in guest',
    'selectCustomer': 'Select customer',
    'registerCustomer': 'Register new customer',
    'noCustomersFound': 'No customers found',
    'total': 'Total',
    'checkout': 'Checkout',
    'searchProducts': 'Search products…',
    'all': 'All',
    'inStock': '{{count}} in stock',
    'pay': 'Pay',
    'cash': 'Cash',
    'card': 'Card',
    'promotionCode': 'Promotion code',
    'cashReceived': 'Cash received',
    'insufficientCash': 'Insufficient cash',
    'subtotal': 'Subtotal',
    'discount': 'Discount',
    'tax': 'Tax',
    'paid': 'Paid ({{method}})',
    'change': 'Change',
    'done': 'Done',
    'orderId': 'Order #{{id}}',
    'load': 'Load',
    'noCompletedOrders': 'No completed orders yet',
    'productId': 'Product #{{id}}',
    'refundTotal': 'Refund total: {{total}}',
    'refundSelected': 'Refund selected items',
    'selectAtLeastOne': 'Select at least one item to refund',
    'refundCreated': 'Refund created successfully',
    'salesSummary': 'Sales summary',
    'grossRevenue': 'Gross revenue',
    'discounts': 'Discounts',
    'netRevenue': 'Net revenue',
    'orders': 'Orders',
    'avgOrder': 'Avg order',
    'lowStock': 'Low stock',
    'healthyStock': 'All product stock levels are healthy.',
    'countedCash': 'Counted cash',
    'countedNonCash': 'Counted non-cash (optional)',
    'reconcileClose': 'Reconcile & close drawer',
    'shiftReconciled': 'Shift reconciled',
    'cashSales': 'Cash sales',
    'nonCashSales': 'Non-cash sales',
    'expectedCash': 'Expected cash',
    'variance': 'Variance',
    'newProduct': 'New product',
    'editProduct': 'Edit {{name}}',
    'name': 'Name',
    'sku': 'SKU',
    'price': 'Price',
    'stock': 'Stock',
    'category': 'Category',
    'save': 'Save',
    'cancel': 'Cancel',
    'newCustomer': 'New customer',
    'phone': 'Phone',
    'region': 'Region',
    'regionDefault': 'Default (follow store settings)',
    'toggleTheme': 'Toggle theme',
  },
  'id': {
    'appTitle': 'OctoPOS',
    'signIn': 'Masuk',
    'signOut': 'Keluar',
    'createAccount': 'Buat akun',
    'register': 'Daftar',
    'alreadyHaveAccount': 'Sudah punya akun? Masuk',
    'newCashierRegister': 'Kasir baru? Daftar',
    'email': 'Email',
    'password': 'Kata sandi',
    'fullName': 'Nama lengkap',
    'validEmail': 'Email valid diperlukan',
    'minPassword': 'Min. 8 karakter',
    'accountLocked': 'Akun terkunci sementara. Coba lagi nanti.',
    'badCredentials': 'Email atau kata sandi salah.',
    'cannotReachServer':
        'Tidak dapat menghubungi server. Apakah backend berjalan?',
    'required': 'Wajib diisi',
    'back': 'Kembali',
    'create': 'Buat',
    'pos': 'POS',
    'products': 'Produk',
    'customers': 'Pelanggan',
    'reports': 'Laporan',
    'refunds': 'Pengembalian',
    'endShift': 'Akhiri shift',
    'openDrawer': 'Buka laci',
    'noOpenDrawer':
        'Tidak ada laci terbuka. Buka laci sebelum menerima pesanan.',
    'drawerOpen': 'Laci #{{id}} terbuka',
    'cart': 'Keranjang',
    'cartEmpty': 'Keranjang kosong',
    'cartCount': 'Keranjang ({{count}})',
    'customer': 'Pelanggan',
    'guest': 'Tamu',
    'walkInGuest': 'Tamu tanpa daftar',
    'selectCustomer': 'Pilih pelanggan',
    'registerCustomer': 'Daftarkan pelanggan baru',
    'noCustomersFound': 'Tidak ada pelanggan ditemukan',
    'total': 'Total',
    'checkout': 'Bayar',
    'searchProducts': 'Cari produk…',
    'all': 'Semua',
    'inStock': 'Stok {{count}}',
    'pay': 'Bayar',
    'cash': 'Tunai',
    'card': 'Kartu',
    'promotionCode': 'Kode promosi',
    'cashReceived': 'Uang diterima',
    'insufficientCash': 'Uang tidak cukup',
    'subtotal': 'Subtotal',
    'discount': 'Diskon',
    'tax': 'Pajak',
    'paid': 'Dibayar ({{method}})',
    'change': 'Kembalian',
    'done': 'Selesai',
    'orderId': 'Pesanan #{{id}}',
    'load': 'Muat',
    'noCompletedOrders': 'Belum ada pesanan selesai',
    'productId': 'Produk #{{id}}',
    'refundTotal': 'Total refund: {{total}}',
    'refundSelected': 'Refund item terpilih',
    'selectAtLeastOne': 'Pilih minimal satu item untuk direfund',
    'refundCreated': 'Refund berhasil dibuat',
    'salesSummary': 'Ringkasan penjualan',
    'grossRevenue': 'Pendapatan kotor',
    'discounts': 'Diskon',
    'netRevenue': 'Pendapatan bersih',
    'orders': 'Pesanan',
    'avgOrder': 'Rata-rata pesanan',
    'lowStock': 'Stok menipis',
    'healthyStock': 'Semua stok produk sehat.',
    'countedCash': 'Tunai dihitung',
    'countedNonCash': 'Non-tunai dihitung (opsional)',
    'reconcileClose': 'Rekonsiliasi & tutup laci',
    'shiftReconciled': 'Shift selesai direkonsiliasi',
    'cashSales': 'Penjualan tunai',
    'nonCashSales': 'Penjualan non-tunai',
    'expectedCash': 'Tunai diperkirakan',
    'variance': 'Selisih',
    'newProduct': 'Produk baru',
    'editProduct': 'Edit {{name}}',
    'name': 'Nama',
    'sku': 'SKU',
    'price': 'Harga',
    'stock': 'Stok',
    'category': 'Kategori',
    'save': 'Simpan',
    'cancel': 'Batal',
    'newCustomer': 'Pelanggan baru',
    'phone': 'Telepon',
    'region': 'Region',
    'regionDefault': 'Bawaan (ikuti pengaturan toko)',
    'toggleTheme': 'Ganti tema',
  },
};

class AppStrings {
  const AppStrings(this._strings);

  final Map<String, String> _strings;

  String of(String key, {Map<String, Object> args = const {}}) {
    var text = _strings[key] ?? _translations['en']![key] ?? key;
    for (final entry in args.entries) {
      text = text.replaceAll('{{${entry.key}}}', entry.value.toString());
    }
    return text;
  }
}

final stringsProvider = Provider<AppStrings>((ref) {
  final language = ref.watch(localizationControllerProvider).language;
  return AppStrings(_translations[language] ?? _translations['en']!);
});
